# Member panel agent dashboard resources
helpdesk_router_member_authentication_resources:
    resource: "@UVDeskCoreBundle/Resources/config/routes/auth.yaml"

# Member panel agent dashboard resources
helpdesk_router_member_panel_resources:
    resource: "@UVDeskCoreBundle/Resources/config/routes/members.yaml"

# Member panel agent dashboard resources
helpdesk_router_member_ticket_resources:
    resource: "@UVDeskCoreBundle/Resources/config/routes/tickets.yaml"

# Member panel customer dashboard resources
helpdesk_router_member_customer_resources:
    resource: "@UVDeskCoreBundle/Resources/config/routes/customers.yaml"
