# Mailbox Resources
helpdesk_member_mailbox_collection:
    path:     /mailbox
    # controller: Webkul\UVDesk\CoreBundle\Channels\MailboxChannel::listMailboxCollection
    controller: Webkul\UVDesk\CoreBundle\Channels\MailboxChannelXHR::listMailboxCollection
    defaults: { panelId: 'channels' }

helpdesk_member_mailbox_channel_verify_mail_auto_forwarding:
    path:     /mailbox/xhr/auto-forwarding-check/{mailboxId}
    controller: Webkul\UVDesk\CoreBundle\Channels\MailboxChannelXHR::verifyEmailForwardingXHR
    defaults: { mailboxId : 0 } 

helpdesk_member_mailbox_channel_xhr:
    path:     /mailbox/xhr/{mailboxId}
    controller: Webkul\UVDesk\CoreBundle\Channels\MailboxChannelXHR::updateMailboxChannelXHR
    defaults: { mailboxId: 0 } 